_commit: v0.1.0
_src_path: https://github.com/betabitplus/ternforge-template-infra-repository.git
copyright_year: '2026'
github_owner: betabitplus
project_title: Ternforge Infra Sample
repository_name: ternforge-infra-sample
